steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/jona-container-project/github.com/jonathandsouza/demo-container:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/jona-container-project/github.com/jonathandsouza/demo-container:$SHORT_SHA']
  
  
